# -*- coding: utf-8 -*-
"""Tic Tac Toe.ipynb
Tic Tac Toe (井字格) - 互動式按鈕版
請在 Jupyter Notebook 或 Google Colab 執行
需要安裝 ipywidgets
!pip install ipywidgets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNLP8zAXYdIMkv7PWV3JJE4C-p0RwgsE

"""

import ipywidgets as widgets
from IPython.display import display

import ipywidgets as widgets
from IPython.display import display, clear_output

board = [[" " for _ in range(3)] for _ in range(3)]
current_player = ["X"]

def check_winner(board, player):
    win = [player] * 3
    for row in board:
        if row == win:
            return True
    for col in range(3):
        if [board[row][col] for row in range(3)] == win:
            return True
    if [board[i][i] for i in range(3)] == win or [board[i][2-i] for i in range(3)] == win:
        return True
    return False

def game_end():
    if any(check_winner(board, p) for p in ["X", "O"]):
        return True
    return all(cell != " " for row in board for cell in row)

def on_button_click(btn):
    r, c = btn.row, btn.col
    if board[r][c] == " " and not game_end():
        board[r][c] = current_player[0]
        btn.description = current_player[0]
        btn.style.button_color = "#90ee90" if current_player[0]=="X" else "#add8e6"
        if check_winner(board, current_player[0]):
            status.value = f"{current_player[0]} 勝利！"
        elif all(cell != " " for row in board for cell in row):
            status.value = "平手！"
        else:
            current_player[0] = "O" if current_player[0] == "X" else "X"
            status.value = f"輪到 {current_player[0]}"
    else:
        pass

buttons = []
for i in range(3):
    row = []
    for j in range(3):
        b = widgets.Button(description=" ", layout=widgets.Layout(width="50px", height="50px"))
        b.row, b.col = i, j
        b.on_click(on_button_click)
        row.append(b)
    buttons.append(row)

status = widgets.Label(value="輪到 X")
ui = widgets.VBox([widgets.HBox(row) for row in buttons] + [status])
display(ui)